object HostGroup "CLARIN K-LIPI" {
    display_name = "CLARIN K-Centre for Indian LIPI"
}

object Host "CLARIN K-LIPI" {
    import "clarin-generic-host"
    address = "jpnnationalcentre.com"
    display_name = "CLARIN K-Centre for Indian LIPI"
    groups = ["CLARIN", "CLARIN K-LIPI"]
    vars.geolocation = "22.524831731905458,75.92319074081068"
    vars.http_ssl = true
    vars.http_uri = "/CLARIN-K-Centre-Indian-LIPI-JPN-National-Centre-Excellence.html"
    vars.http_vhost = "jpnnationalcentre.com"
    vars.ssl_certs["jpnnationalcentre.com"] = {
        ssl_cert_address = "jpnnationalcentre.com"
        ssl_cert_altnames = true
        ssl_cert_cn = "jpnnationalcentre.com"
        ssl_cert_critical = 7
        ssl_cert_warn = 10
    }
}
