object HostGroup "KeTa" {
    display_name = "Estonian Language Data Infrastructure"
}

object Host "KeTa" {
    import "clarin-generic-host"
    address = "eki.ee"
    display_name = "Estonian Language Data Infrastructure"
    groups = ["CLARIN", "KeTa"]
    vars.geolocation = "59.43174205759368,24.743256910320298"
    vars.http_ssl = true
    vars.http_uri = "/teadus-ja-arendustegevus/teadustaristu/"
    vars.http_vhost = "eki.ee"
    vars.oaipmh_endpoints["14"] = {
        oaipmh_endpoint = "https://metashare.ut.ee/oai_pmh/"
    }
    vars.ssl_certs["eki.ee"] = {
        ssl_cert_address = "eki.ee"
        ssl_cert_altnames = true
        ssl_cert_cn = "eki.ee"
        ssl_cert_critical = 7
        ssl_cert_warn = 10
    }
    vars.ssl_certs["metashare.ut.ee"] = {
        ssl_cert_address = "metashare.ut.ee"
        ssl_cert_altnames = true
        ssl_cert_cn = "metashare.ut.ee"
        ssl_cert_critical = 7
        ssl_cert_warn = 10
    }
}
